import datetime
from datetime import date
from decimal import Decimal

from sqlalchemy.orm import Session
from starlette import status

from database import SessionLocal
from test.executor.customer import CustomerAPIExecutor


class TestSimpleCaseCustomer:
    executor_admin = CustomerAPIExecutor()
    def test_customer_created_profile(self):
        ...
    def test_customer_get_profile_by_id(self):
        ...
    def test_customer_update_profile(self):
        ...
    def test_customer_get_cart_items(self):
        ...
    def test_customer_insert_cart_item(self):
        ...
    def test_customer_get_cart_item_by_id(self):
        ...
    def test_customer_update_cart_item(self):
        ...
    def test_customer_delete_cart_item(self):
        ...
    def test_customer_get_orders(self):
        ...
    def test_customer_place_order(self):
        ...
    def test_customer_get_products(self):
        ...
    def test_customer_get_product_by_id(self):
        ...